<?php

namespace ElevationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoadRepository extends EntityRepository
{
}
